
@jwt_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc1MTU1NDY5MCwiZXhwIjoxNzUxNTU4MjkwLCJpc3MiOiJRdWVzdHkifQ.MIKpuBzVavBmnbPo5XVpO-quLkwweqeo89CwFXq6KHU
POST http://localhost:8080/project/new
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "My New Project",
  "description": "This is a test project"
}